### ISSUE TITLE
Subscribers can edit arbitrary events

### ISSUE THREAD

**Issue by powerriegel** [letsmeet-click/letsmeet.click#67] opened 2018-04-08 19:43 UTC
Hello,

subscribers of my community can edit any event i publish. And I myslf can edit events in other groups where I'm only subscriber. 

This seems to be a big security breach! There seems to be no privilege check before editing and/or before saving. Any attacker could delete all the events he is able to see. 

Regards

**Comment by powerriegel** [comment] 2018-04-08 20:02
I can also edit arbitrary groupy, i.e. not the events but the groups description. No need to be subscriber in these groups. Just need to be logged in. 

That means: A logged in user can delete all groups and events on lets meet.

**Comment by mfa** [comment] 2018-04-09 08:52
I don't see why this errors occurs, so I have to stop the public letsmeet.click instance until this issue is resolved. Sorry about that.

**Comment by powerriegel** [comment] 2018-04-09 10:09
I'm logged in via Facebook if that helps to reproduce the error. My Twitter account is connected, too.

**Comment by mfa** [comment] 2018-04-09 12:03
should be fixed. I updated everything. especially django-rules and django 2.0.
if you can reproduce the problem again, please re-open ticket.

**Closed as completed by mfa** 2018-04-09 12:03 UTC

**Comment by powerriegel** [comment] 2018-04-09 12:17
Now, I'm unable to edit my own events and groups.

**Comment by mfa** [comment] 2018-04-09 12:26
cannot reproduce :(
